### ISSUE TITLE
Fix config.json relative path

### ISSUE THREAD

**Issue by quelqun007** [baudev/Nexecur-Unofficial-API#2]
When using this repository as a submodule in another project, the configuration file `config.json` is not taken into account due to wrong path in `Core.ts`  : 

line 5 of Core.ts : 
```
let userConfig : UserConfiguration = require('../config.json')
```

**Comment by baudev** [comment]
This repository is still not developed to be used as a submodule.
This will be fixed in this tonight's commits.
